loam_interface:
  ros__parameters:
    use_sim_time: false
    state_estimation_topic: "tower/mapping/odometry"
    registered_scan_topic: "tower/mapping/cloud"
    odom_frame: odom
    slam_odom_frame: mapping_init
    hlidar_frame: hlidar
    lidar_frame: mid360

sensor_scan_generation:
  ros__parameters:
    use_sim_time: false
    lidar_frame: mid360
    footprint_frame: base_footprint

terrain_analysis:
  ros__parameters:
    odom_frame: odom
    use_sim_time: false
    scanVoxelSize: 0.05                 # 点云下采样
    decayTime: 0.5                      # 点云时间差阈值 大于则不会被处理
    noDecayDis: 0.0                     # 点云距离阈值 小于该阈值不考虑时间差
    clearingDis: 0.0                    # 该距离外的点会被清除
    useSorting: True                    # 这个参数开起来就能上坡了；如果 use_sorting,那么就以周围点中的分位点作为地面点，否则以最低点作为地面点；周围其余点相对于地面点的高度作为通过代价，所以对于坡面，有的点的代价是正，有的是负，就相互抵消了；不要与 consider_drop 同时开启，计算上会有冲突
    quantileZ: 0.2                      # useful if use_sorting is enabled.
    considerDrop: False                 # 考虑凹下去的地面,开启则将相对于地面点的高度取绝对值
    limitGroundLift: False
    maxGroundLift: 0.3
    # 以下参数都是在 clear_dy_obs 的情况下才有用的
    clearDyObs: True                    # 清除动态物体的话，有动态物体走过的地方就走不了了
    minDyObsPointNum: 1
    minDyObsDis: 0.3 
    minDyObsAngle: 0.0
    minDyObsRelZ: -0.3
    absDyObsRelZThre: 0.2
    minDyObsVFOV: -28.0
    maxDyObsVFOV: 33.0
    # 
    noDataObstacle: False               # treat no data as obstacle
    noDataBlockSkipNum: 0
    minBlockPointNum: 10
    vehicleHeight: 1.0                  # 小于车辆高度的点才会进行处理
    voxelPointUpdateThre: 100
    voxelTimeUpdateThre: 1.0
    minRelZ: -5.5                       # min_rel_z 以及 max_rel_z 限制了有效点云点的Z值范围，用于对天花板和地板进行处理
    maxRelZ: 2.0
    disRatioZ: 0.1                      # Z 值的最大最小范围由这两个值决定，但是并不等于这两个值，是有一个比例关系的，距离机器人越远，限定范围就越大，这其中考虑了坡度

terrain_analysis_ext:
  ros__parameters:
    odom_frame: odom
    use_sim_time: false
    scanVoxelSize: 0.1
    decayTime: 0.2
    noDecayDis: 0.0
    clearingDis: 20.0
    useSorting: True
    quantileZ: 0.4
    vehicleHeight: 1.0  
    voxelPointUpdateThre: 100
    voxelTimeUpdateThre: 2.0
    lowerBoundZ: -5.5
    upperBoundZ: 2.0
    disRatioZ: 0.1
    checkTerrainConn: False
    terrainUnderVehicle: -0.75
    terrainConnThre: 0.5
    ceilingFilteringThre: 2.0
    localTerrainMapRadius: 4.0
  
pointcloud_to_laserscan:
  ros__parameters:
    use_sim_time: false
    target_frame: base_footprint
    # range
    range_min: 0.35
    range_max: 10.0
    # height
    min_height: 0.1 # -2.0 This value is set to 0.1 to avoid taking obstacle points on the ground when running mapping module in Isaac Sim. 
    max_height: 1.0
    #intensity
    min_intensity: 0.1
    max_intensity: 2.0
    # angle
    angle_min: -3.1415926                   # -M_PI/2
    angle_max: 3.1415926                    # M_PI/2
    angle_increment: 0.00872665             # M_PI/360.0
    scan_time: 0.05
    use_inf: true