
<!-- 底盘 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <link name="base_footprint" />
    <link name="vehicle">
        <visual>
            <geometry>
                <box size="${car_length} ${car_width} ${car_height}" />
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${car_length} ${car_width} ${car_height}" />
            </geometry>
        </collision>
        <xacro:box_inertial_matrix m="3" l="${car_length}" w="${car_width}" h="${car_height}" />
    </link>

    <joint name="vehicle2base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="vehicle" />
        <origin xyz="0.0 0.0 ${car_height/2+distance}" />
    </joint>

    <!-- 车轮宏函数 -->
    <xacro:macro name="wheel_func" params="link_name front_flag left_flag">
        <link name="${link_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <material name="black" />
                <origin rpy="${PI/2} 0.0 0.0" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin rpy="${PI/2} 0.0 0.0" />
            </collision>
            <xacro:sphere_inertial_matrix m="4" r="${wheel_radius}" />
        </link>
        <joint name="${link_name}2vehicle" type="fixed">
            <parent link="vehicle" />
            <child link="${link_name}_wheel" />
            <origin xyz="${wheel_joint_x* front_flag} ${wheel_joint_y* left_flag} ${wheel_joint_z}" />
            <axis xyz="0.0 1.0 0.0" />
        </joint>
    </xacro:macro>

    <xacro:wheel_func link_name="front_left" front_flag="1" left_flag="1" />
    <xacro:wheel_func link_name="front_right" front_flag="1" left_flag="-1" />
    <xacro:wheel_func link_name="back_left" front_flag="-1" left_flag="1" />
    <xacro:wheel_func link_name="back_right" front_flag="-1" left_flag="-1" />

    <link name="lidar_holder">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${holder_radius}" length="${holder_length}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${holder_radius}" length="${holder_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="0.1" r="${holder_radius}" h="${holder_length}" />
    </link>

    <joint name="lidar_holder2vehicle" type="fixed">
        <origin xyz="0.0 0.0 ${car_height/2+holder_length/2}" rpy="0 0 0" />
        <parent link="vehicle" />
        <child link="lidar_holder" />
    </joint>

    <xacro:gazebo_material ref="vehicle" color="Red" />
    <xacro:gazebo_material ref="lidar_holder" color="Black" />
    <xacro:gazebo_material ref="front_left_wheel" color="Black" />
    <xacro:gazebo_material ref="front_right_wheel" color="Black" />
    <xacro:gazebo_material ref="back_left_wheel" color="Black" />
    <xacro:gazebo_material ref="back_right_wheel" color="Black" />

</robot>