<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <xacro:property name="hub_id" value="$(arg hub_id)" />
    <xacro:property name="namespace_prefix" value="${hub_id + '/'}" />
    <xacro:property name="ns" value="$(arg ns)/" />
    <!-- 惯性矩阵 -->
    <!-- sphere球体 -->
    <xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0" iyy="${2*m*r*r/5}"
                iyz="0" izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>
    <!-- cylinder圆柱 -->
    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0"
                izz="${m*r*r/2}" />
        </inertial>
    </xacro:macro>
    <!-- box长方体 -->
    <xacro:macro name="box_inertial_matrix" params="m l w h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(h*h + l*l)/12}" ixy="0" ixz="0"
                iyy="${m*(w*w + l*l)/12}" iyz="0"
                izz="${m*(w*w + h*h)/12}" />
        </inertial>
    </xacro:macro>

    <!-- 底盘尺寸 -->
    <xacro:property name="PI" value="3.14159" />
    <xacro:property name="car_length" value="0.6" />
    <xacro:property name="car_width" value="0.53" />
    <xacro:property name="car_height" value="0.16" />

    <!-- 轮胎尺寸 -->
    <xacro:property name="wheel_radius" value="0.12" />
    <xacro:property name="wheel_length" value="-0.02" />

    <!-- 雷达杆的半径和长度 -->
    <xacro:property name="holder_radius" value="0.03" />
    <xacro:property name="holder_length" value="0.16" />

    <!-- 轮胎关节偏移量 -->
    <xacro:property name="wheel_joint_x" value="0.2" />
    <xacro:property name="wheel_joint_y" value="${car_width/2+wheel_length/2}" />
    <xacro:property name="wheel_joint_z" value="${-(car_height/2 + distance - wheel_radius)}" />

    <!-- 离地间距 -->
    <xacro:property name="distance" value="0.14" />

    <!-- 2d雷达尺寸 -->
    <xacro:property name="laser_radius" value="0.05" />
    <xacro:property name="laser_length" value="0.05" />

    <!-- rviz颜色封装 -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0" />
    </material>
    <material name="red">
        <color rgba="1.0 0.0 0.0 1.0" />
    </material>
    <material name="yellow">
        <color rgba="1.0 1.0 0.0 1.0" />
    </material>
    <material name="green">
        <color rgba="0.0 1.0 0.0 1.0" />
    </material>

    <!-- gazebo的颜色封装 -->
    <xacro:macro name="gazebo_material" params="ref color">
        <gazebo reference="${ref}">
            <material>Gazebo/${color}</material>
        </gazebo>
    </xacro:macro>

</robot>