<!--24-李东权，1327165187@qq.com-->
<!-- 主文件,整合所有模块 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <gravity>true</gravity>
    <xacro:include filename="property.xacro" />
    <xacro:include filename="car_base.urdf.xacro" />
    <xacro:include filename="sensor/velodyne.urdf.xacro" />
    <!-- <xacro:include filename="sensor/camera.urdf.xacro" /> -->
    <!-- <xacro:include filename="laser.urdf.xacro" /> -->
    <!-- <joint name="camera2base_link" type="fixed">
        <parent link="vehicle" />
        <child link="camera" />
        <origin xyz="0.2 0 0.12" rpy="0 0 0" />
        <axis xyz="0 0 0" />
    </joint> -->

    <!-- <xacro:VLP-16 hub_id="${hub_id}" parent="lidar_holder"  name="velodyne" topic="velodyne_points" hz="10"
        min_range="0.55" samples="350" collision_range="0.56" gpu="false"
        min_angle="-3.14159" max_angle="3.14159" vmin_angle="${-7/180*PI}" vmax_angle="${52/180*PI}">
        <origin xyz="0.0 0.0 ${holder_length/2}" rpy="0 0 0" />
    </xacro:VLP-16> -->
    <xacro:VLP-16 parent="denk/lidar_holder"  name="velodyne" topic="denk/velodyne_points" hz="10"
        min_range="0.55" samples="350" collision_range="0.56" gpu="false"
        min_angle="-3.14159" max_angle="3.14159" >
        <origin xyz="0.0 0.0 ${holder_length/2}" rpy="0 0 0" />
    </xacro:VLP-16>
    <!-- <xacro:VLP-16 parent="vehicle" name="velodyne2" topic="/velodyne_points2" hz="10"
        min_range="0.55" samples="350" collision_range="0.56" gpu="false"
        min_angle="-3.14159" max_angle="0" vmin_angle="${-7/180*PI}" vmax_angle="${52/180*PI}">
        <origin xyz="0.0 -0.2 ${car_height/2+0.02}" rpy="0 0 0" />
    </xacro:VLP-16> -->

    <xacro:include filename="$(find gazebo_sim)/urdf/robot/plugins/gazebo_control_plugin_prefix.xacro" />
    <xacro:gazebo_control_plugin namespace_prefix="${namespace_prefix}" />

</robot>