<robot name="laser" xmlns:xacro="http://wiki.ros.org/xacro">
    <link name="laser">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="0.2" r="${laser_radius}" h="${laser_length}" />
    </link>

    <joint name="laser2vehicle" type="fixed">
        <origin xyz="0.0 -0.2 ${car_height/2+laser_length/2}" rpy="0 -0.0873 ${PI/2}" />
        <parent link="vehicle" />
        <child link="laser" />
    </joint>

    <xacro:gazebo_material ref="laser" color="Black" />

    <!-- laser -->
    <gazebo reference="laser">            <!-- get laser's link name -->
        <sensor type="ray" name="rplidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>   <!--gazebo's
            light can be watched-->
            <update_rate>20</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution> <!--每1度进行一次采样-->
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.18</min>           <!--distance-->
                    <max>30.0</max>
                    <resolution>0.01</resolution>     <!--acuracy-->
                </range>
                <noise>
                    <type>gaussian</type> <!--add
                    gaussian in simulation-->
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser</frameName>
            </plugin>
        </sensor>
    </gazebo>
</robot>
  
  